# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import messages_pb2 as messages__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in messages_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDevice = channel.unary_unary(
                '/GatewayService/RegisterDevice',
                request_serializer=messages__pb2.JoinRequest.SerializeToString,
                response_deserializer=messages__pb2.JoinReply.FromString,
                _registered_method=True)
        self.GetAddress = channel.unary_unary(
                '/GatewayService/GetAddress',
                request_serializer=messages__pb2.Empty.SerializeToString,
                response_deserializer=messages__pb2.Address.FromString,
                _registered_method=True)
        self.GetSensorsReport = channel.unary_unary(
                '/GatewayService/GetSensorsReport',
                request_serializer=messages__pb2.ClientReply.SerializeToString,
                response_deserializer=messages__pb2.SensorsReport.FromString,
                _registered_method=True)
        self.GetActuatorsReport = channel.unary_unary(
                '/GatewayService/GetActuatorsReport',
                request_serializer=messages__pb2.ClientReply.SerializeToString,
                response_deserializer=messages__pb2.ActuatorsReport.FromString,
                _registered_method=True)
        self.GetSensorData = channel.unary_unary(
                '/GatewayService/GetSensorData',
                request_serializer=messages__pb2.ClientReply.SerializeToString,
                response_deserializer=messages__pb2.SensorData.FromString,
                _registered_method=True)
        self.GetActuatorUpdate = channel.unary_unary(
                '/GatewayService/GetActuatorUpdate',
                request_serializer=messages__pb2.ClientReply.SerializeToString,
                response_deserializer=messages__pb2.ActuatorUpdate.FromString,
                _registered_method=True)
        self.SendActuatorCommand = channel.unary_unary(
                '/GatewayService/SendActuatorCommand',
                request_serializer=messages__pb2.ActuatorCommand.SerializeToString,
                response_deserializer=messages__pb2.ActuatorComply.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterDevice(self, request, context):
        """Dispositivos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSensorsReport(self, request, context):
        """Clientes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActuatorsReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSensorData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActuatorUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendActuatorCommand(self, request, context):
        """Comandos para atuadores
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDevice,
                    request_deserializer=messages__pb2.JoinRequest.FromString,
                    response_serializer=messages__pb2.JoinReply.SerializeToString,
            ),
            'GetAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddress,
                    request_deserializer=messages__pb2.Empty.FromString,
                    response_serializer=messages__pb2.Address.SerializeToString,
            ),
            'GetSensorsReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSensorsReport,
                    request_deserializer=messages__pb2.ClientReply.FromString,
                    response_serializer=messages__pb2.SensorsReport.SerializeToString,
            ),
            'GetActuatorsReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActuatorsReport,
                    request_deserializer=messages__pb2.ClientReply.FromString,
                    response_serializer=messages__pb2.ActuatorsReport.SerializeToString,
            ),
            'GetSensorData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSensorData,
                    request_deserializer=messages__pb2.ClientReply.FromString,
                    response_serializer=messages__pb2.SensorData.SerializeToString,
            ),
            'GetActuatorUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActuatorUpdate,
                    request_deserializer=messages__pb2.ClientReply.FromString,
                    response_serializer=messages__pb2.ActuatorUpdate.SerializeToString,
            ),
            'SendActuatorCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendActuatorCommand,
                    request_deserializer=messages__pb2.ActuatorCommand.FromString,
                    response_serializer=messages__pb2.ActuatorComply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GatewayService/RegisterDevice',
            messages__pb2.JoinRequest.SerializeToString,
            messages__pb2.JoinReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GatewayService/GetAddress',
            messages__pb2.Empty.SerializeToString,
            messages__pb2.Address.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSensorsReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GatewayService/GetSensorsReport',
            messages__pb2.ClientReply.SerializeToString,
            messages__pb2.SensorsReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActuatorsReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GatewayService/GetActuatorsReport',
            messages__pb2.ClientReply.SerializeToString,
            messages__pb2.ActuatorsReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GatewayService/GetSensorData',
            messages__pb2.ClientReply.SerializeToString,
            messages__pb2.SensorData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActuatorUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GatewayService/GetActuatorUpdate',
            messages__pb2.ClientReply.SerializeToString,
            messages__pb2.ActuatorUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendActuatorCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GatewayService/SendActuatorCommand',
            messages__pb2.ActuatorCommand.SerializeToString,
            messages__pb2.ActuatorComply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
