/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_PROTOS_MENSAGEM_PB_H_INCLUDED
#define PB_PROTOS_MENSAGEM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _DispositivoInfo {
    char tipo[64];
    char id[64];
    char ip[64];
    int32_t porta;
    char estado[64];
} DispositivoInfo;

typedef struct _Comando {
    char id[64];
    char acao[64];
    char valor[64];
} Comando;

typedef struct _Estado {
    char id[64];
    char estado[64];
} Estado;

typedef struct _LeituraSensor {
    char id[64];
    char tipo[64];
    char valor[64];
    char timestamp[64];
} LeituraSensor;

typedef struct _ListaDispositivos {
    pb_callback_t dispositivos;
} ListaDispositivos;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DispositivoInfo_init_default             {"", "", "", 0, ""}
#define Comando_init_default                     {"", "", ""}
#define Estado_init_default                      {"", ""}
#define LeituraSensor_init_default               {"", "", "", ""}
#define ListaDispositivos_init_default           {{{NULL}, NULL}}
#define DispositivoInfo_init_zero                {"", "", "", 0, ""}
#define Comando_init_zero                        {"", "", ""}
#define Estado_init_zero                         {"", ""}
#define LeituraSensor_init_zero                  {"", "", "", ""}
#define ListaDispositivos_init_zero              {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define DispositivoInfo_tipo_tag                 1
#define DispositivoInfo_id_tag                   2
#define DispositivoInfo_ip_tag                   3
#define DispositivoInfo_porta_tag                4
#define DispositivoInfo_estado_tag               5
#define Comando_id_tag                           1
#define Comando_acao_tag                         2
#define Comando_valor_tag                        3
#define Estado_id_tag                            1
#define Estado_estado_tag                        2
#define LeituraSensor_id_tag                     1
#define LeituraSensor_tipo_tag                   2
#define LeituraSensor_valor_tag                  3
#define LeituraSensor_timestamp_tag              4
#define ListaDispositivos_dispositivos_tag       1

/* Struct field encoding specification for nanopb */
#define DispositivoInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   tipo,              1) \
X(a, STATIC,   SINGULAR, STRING,   id,                2) \
X(a, STATIC,   SINGULAR, STRING,   ip,                3) \
X(a, STATIC,   SINGULAR, INT32,    porta,             4) \
X(a, STATIC,   SINGULAR, STRING,   estado,            5)
#define DispositivoInfo_CALLBACK NULL
#define DispositivoInfo_DEFAULT NULL

#define Comando_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   acao,              2) \
X(a, STATIC,   SINGULAR, STRING,   valor,             3)
#define Comando_CALLBACK NULL
#define Comando_DEFAULT NULL

#define Estado_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   estado,            2)
#define Estado_CALLBACK NULL
#define Estado_DEFAULT NULL

#define LeituraSensor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   tipo,              2) \
X(a, STATIC,   SINGULAR, STRING,   valor,             3) \
X(a, STATIC,   SINGULAR, STRING,   timestamp,         4)
#define LeituraSensor_CALLBACK NULL
#define LeituraSensor_DEFAULT NULL

#define ListaDispositivos_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  dispositivos,      1)
#define ListaDispositivos_CALLBACK pb_default_field_callback
#define ListaDispositivos_DEFAULT NULL
#define ListaDispositivos_dispositivos_MSGTYPE DispositivoInfo

extern const pb_msgdesc_t DispositivoInfo_msg;
extern const pb_msgdesc_t Comando_msg;
extern const pb_msgdesc_t Estado_msg;
extern const pb_msgdesc_t LeituraSensor_msg;
extern const pb_msgdesc_t ListaDispositivos_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DispositivoInfo_fields &DispositivoInfo_msg
#define Comando_fields &Comando_msg
#define Estado_fields &Estado_msg
#define LeituraSensor_fields &LeituraSensor_msg
#define ListaDispositivos_fields &ListaDispositivos_msg

/* Maximum encoded size of messages (where known) */
/* ListaDispositivos_size depends on runtime parameters */
#define Comando_size                             195
#define DispositivoInfo_size                     271
#define Estado_size                              130
#define LeituraSensor_size                       260
#define PROTOS_MENSAGEM_PB_H_MAX_SIZE            DispositivoInfo_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
