/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "mensagem.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(DispositivoInfo, DispositivoInfo, 2)


PB_BIND(Comando, Comando, AUTO)


PB_BIND(Estado, Estado, AUTO)


PB_BIND(LeituraSensor, LeituraSensor, 2)


PB_BIND(ListaDispositivos, ListaDispositivos, AUTO)



